version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn export
      - run: touch out/.nojekyll
      - run: ./scripts/deploy-ghpages.sh build
