version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: ./deploy.sh build
