version: 2.0

jobs:
  build:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: ./deploy.sh build

workflows:
  version: 2
  commit:
    jobs:
      - build
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
